# Generated by Django 3.2.9 on 2021-12-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_completed',
        ),
    ]
